### PR TITLE
Added facts about Eggs.

### PR DESCRIPTION
**Pull request by Veerangana-Dash**
3 interesting and unique facts added about Eggs and their nutritional value in the facts.txt file.

### CODE REVIEW

**Review by rahuldecoded — CHANGES_REQUESTED** [review]
LGTM, just add commas after every facts.

**Comment by Veerangana-Dash** [comment]
Added Commas. edited facts.txt with egg facts

**Comment by rahuldecoded** [comment]
@Veerangana-Dash LGTM thanks.
Do you know python/php/nodejs?

**Comment by Veerangana-Dash** [comment]
Welcome.
I am learning Python currently. Still a beginner.

**Comment by rahuldecoded** [comment]
Have you ever played with APIs? It just need very basic things like list, dict and other fundamental things.
If you're interested in more interesting work, feel free to mail me @ 2806rahul@gmail.com

**Comment by Veerangana-Dash** [comment]
I have tried my hand at some google APIs for a website I was developing. So I do have an idea of how those work.
Sounds great to me. Will get in touch with you soon.

**Pull request merged**
