### PR TITLE
Added two carrot facts

### PR DESCRIPTION
**Pull request by dtoc**
#hacktoberfest

Added two carrot facts.

### CODE REVIEW

**Comment by rahuldecoded** [comment]
Comment the issue number

**Comment by rahuldecoded** [comment]
Would you like to contribute in the project?

**Comment by dtoc** [comment]
@rahuldecoded Sure, as long as this isn't your homework. We should scrape a list of vegetables/fruits/foods from Wikipedia or the internet in general and then build a module that dynamically generates a list of lists for all of those. Adding facts by hand is going to be a pain. It'd also be cool if someone could tell the bot "Hey I want to know more about X food or Y vegetable" and the bot could log that request for additional research.

**Comment by rahuldecoded** [comment]
@dtoc great.

**Pull request merged**
