### PR TITLE
Fixing erros

### PR DESCRIPTION
**Pull request by BrunoGomesCoelho**
Fixing alphabetical ordering, some duplicates entries, lack of tabs in some lines.

### CODE REVIEW

**Comment by BrunoGomesCoelho** [comment]
#101

**Comment by dtoc** [comment]
Please fix the merge conflicts and the indentation. Then I can merge.

**Comment by BrunoGomesCoelho** [comment]
Fixed!

**Comment by dtoc** [comment]
Good work!

**Pull request merged**
